"use client";

import { useServerInsertedHTML } from "next/navigation";

import { globalStyles } from "../../lib/global";
import { getCssText } from "../../stoop.theme";

/**
 * Injects SSR-generated CSS into the document head.
 * Uses Next.js streaming SSR to capture styles as components render.
 *
 * How it works:
 * 1. Global styles are injected first (CSS reset, base styles)
 * 2. During SSR, useServerInsertedHTML captures all CSS generated by components
 * 3. CSS is injected into a <style id="stoop-ssr"> tag in the HTML stream
 * 4. On client hydration, the same tag is reused (no FOUC)
 * 5. Theme-specific CSS variables are included based on initialTheme
 *
 * @param initialTheme - The initial theme name (e.g., "light" or "dark")
 */
export function Styles({ initialTheme }: { initialTheme: string }): null {
  useServerInsertedHTML(() => {
    globalStyles();
    const cssText = getCssText(initialTheme);

    if (!cssText) {
      return null;
    }

    return (
      <style
        dangerouslySetInnerHTML={{ __html: cssText }}
        id="stoop-ssr"
        suppressHydrationWarning
      />
    );
  });

  return null;
}
