/**
 * Shared constants used throughout the library.
 * Includes cache size limits and nesting depth limits.
 */

import type { CSS, ThemeScale } from "./types";

export const EMPTY_CSS: CSS = Object.freeze({});

export const MAX_CSS_CACHE_SIZE = 10000;
export const MAX_CLASS_NAME_CACHE_SIZE = 5000;
export const MAX_CSS_NESTING_DEPTH = 10;

/**
 * Approved theme scales - only these scales are allowed in theme objects.
 */
export const APPROVED_THEME_SCALES: ReadonlyArray<ThemeScale> = [
  "colors",
  "opacities",
  "space",
  "radii",
  "sizes",
  "fonts",
  "fontWeights",
  "fontSizes",
  "lineHeights",
  "letterSpacings",
  "shadows",
  "zIndices",
  "transitions",
] as const;

/**
 * Default themeMap mapping CSS properties to theme scales.
 * Covers common CSS properties for zero-config experience.
 * Missing properties gracefully fallback to pattern-based auto-detection.
 */
export const DEFAULT_THEME_MAP: Record<string, ThemeScale> = {
  accentColor: "colors",
  animation: "transitions",
  animationDelay: "transitions",
  animationDuration: "transitions",
  animationTimingFunction: "transitions",
  backdropFilter: "shadows",
  background: "colors",
  backgroundColor: "colors",
  blockSize: "sizes",
  border: "colors",
  borderBlockColor: "colors",
  borderBlockEndColor: "colors",
  borderBlockStartColor: "colors",
  borderBottomColor: "colors",
  borderBottomLeftRadius: "radii",
  borderBottomRightRadius: "radii",
  borderColor: "colors",
  borderEndEndRadius: "radii",
  borderEndStartRadius: "radii",
  borderInlineColor: "colors",
  borderInlineEndColor: "colors",
  borderInlineStartColor: "colors",
  borderLeftColor: "colors",
  borderRadius: "radii",
  borderRightColor: "colors",
  borderStartEndRadius: "radii",
  borderStartStartRadius: "radii",
  borderTopColor: "colors",
  borderTopLeftRadius: "radii",
  borderTopRightRadius: "radii",
  bottom: "space",
  boxShadow: "shadows",
  caretColor: "colors",
  color: "colors",
  columnGap: "space",
  columnRuleColor: "colors",
  fill: "colors",
  filter: "shadows",
  flexBasis: "sizes",
  floodColor: "colors",
  font: "fontSizes",
  fontFamily: "fonts",
  fontSize: "fontSizes",
  fontWeight: "fontWeights",
  gap: "space",
  gridColumnGap: "space",
  gridGap: "space",
  gridRowGap: "space",
  height: "sizes",
  inlineSize: "sizes",
  inset: "space",
  insetBlock: "space",
  insetBlockEnd: "space",
  insetBlockStart: "space",
  insetInline: "space",
  insetInlineEnd: "space",
  insetInlineStart: "space",
  left: "space",
  letterSpacing: "letterSpacings",
  lightingColor: "colors",
  lineHeight: "lineHeights",
  margin: "space",
  marginBlock: "space",
  marginBlockEnd: "space",
  marginBlockStart: "space",
  marginBottom: "space",
  marginInline: "space",

  marginInlineEnd: "space",
  marginInlineStart: "space",
  marginLeft: "space",
  marginRight: "space",
  marginTop: "space",
  maxBlockSize: "sizes",
  maxHeight: "sizes",
  maxInlineSize: "sizes",
  maxWidth: "sizes",
  minBlockSize: "sizes",
  minHeight: "sizes",
  minInlineSize: "sizes",
  minWidth: "sizes",
  opacity: "opacities",
  outline: "colors",
  outlineColor: "colors",
  padding: "space",
  paddingBlock: "space",
  paddingBlockEnd: "space",
  paddingBlockStart: "space",
  paddingBottom: "space",
  paddingInline: "space",
  paddingInlineEnd: "space",
  paddingInlineStart: "space",
  paddingLeft: "space",
  paddingRight: "space",
  paddingTop: "space",
  right: "space",
  rowGap: "space",
  size: "sizes",
  stopColor: "colors",
  stroke: "colors",
  textDecorationColor: "colors",
  textEmphasisColor: "colors",
  textShadow: "shadows",
  top: "space",
  transition: "transitions",
  transitionDelay: "transitions",
  transitionDuration: "transitions",
  transitionProperty: "transitions",
  transitionTimingFunction: "transitions",
  width: "sizes",
  zIndex: "zIndices",
};

export const STOOP_COMPONENT_SYMBOL = Symbol.for("stoop.component");
