import type { CSSFunction } from "./types.js";

let _cssCounter = 0;

/**
 * Runtime stub for css().
 * Returns a placeholder class name so config/utility files can safely call css()
 * outside the SWC plugin. The real class names are generated by the compiler.
 */
export const css: CSSFunction = ((_styles: unknown) => {
  return `stoop-css-${_cssCounter++}`;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
}) as any;
