import type { KeyframesFunction } from "./types.js";

let _kfCounter = 0;

/**
 * Runtime stub for keyframes().
 * Returns a placeholder name so config files can safely call keyframes()
 * outside the SWC plugin (e.g. theme.config.ts loaded by jiti at build time).
 * The real keyframe names are generated by the compiler.
 */
export const keyframes: KeyframesFunction = ((_definition: Record<string, unknown>) => {
  return `stoop-kf-${_kfCounter++}`;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
}) as any;
